### ISSUE TITLE
MultiBiController doesn't send output midi

### ISSUE THREAD

**Issue by riwid** [ThomasHelzle/Toms_Bitwig_Scripts#5]
Thanks for great scripts.

For some time the MultiBiController script doesn't output midi to my midicontroller (Dj Tech Tools Midi fighter Twister) with endless rotary knobs with visual feedback. It used to work fine and I haven't been changing anything in the sets where I mapped the controller. 

Best
Richard

**Comment by ThomasHelzle** [comment]
This was a Bitwig Bug, It's fixed in the upcoming 2.3 - try the beta and let me know if you still have trouble.

Cheers,

Tom
